#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/easy_api_doc/engine', __FILE__)

# require 'rails/all'
require "action_controller/railtie"
require "rails/test_unit/railtie"
require "sprockets/railtie"
# instead of rails/all

require 'rails/engine/commands'
